# Generated by Django 5.2 on 2025-04-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='levels',
            field=models.ManyToManyField(related_name='programs', to='workout_app.sportsmanlevel'),
        ),
    ]
