# Generated by Django 5.2 on 2025-04-24 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0002_program_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='levels',
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.city'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.sportsmanlevel'),
        ),
        migrations.AlterField(
            model_name='sportsman',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.program'),
        ),
        migrations.AddField(
            model_name='program',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.sportsmanlevel'),
        ),
    ]
