# Generated by Django 5.2 on 2025-04-24 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0003_remove_program_levels_alter_sportsman_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='levels',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='workout_app.sportsmanlevel'),
        ),
    ]
