# Generated by Django 5.2 on 2025-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0004_alter_program_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportsman',
            name='password',
            field=models.CharField(default='password', max_length=100),
            preserve_default=False,
        ),
    ]
