# Generated by Django 5.2 on 2025-04-29 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0006_sportsman_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsman',
            name='program',
        ),
        migrations.AddField(
            model_name='sportsman',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sportsman',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='sportsman',
            name='weight',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BaseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.sportsmanlevel')),
            ],
        ),
        migrations.CreateModel(
            name='BaseExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=100)),
                ('default_reps', models.PositiveIntegerField()),
                ('default_sets', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_app.baseprogram')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.baseprogram')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.sportsman')),
            ],
        ),
        migrations.CreateModel(
            name='UserExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('muscle_group', models.CharField(max_length=100)),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_app.userprogram')),
            ],
        ),
        migrations.DeleteModel(
            name='Program',
        ),
    ]
