# Generated by Django 5.2 on 2025-04-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0007_remove_sportsman_program_sportsman_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('base_multiplier', models.FloatField(help_text='Multiplier relative to user body weight (e.g. 0.7 for chest)')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprogram',
            name='base_program',
        ),
        migrations.RemoveField(
            model_name='baseexercise',
            name='program',
        ),
        migrations.RemoveField(
            model_name='userexercise',
            name='program',
        ),
        migrations.RemoveField(
            model_name='baseexercise',
            name='default_reps',
        ),
        migrations.RemoveField(
            model_name='baseexercise',
            name='default_sets',
        ),
        migrations.AddField(
            model_name='baseexercise',
            name='bodyweight',
            field=models.BooleanField(default=True, help_text='If true, uses body weight as resistance'),
        ),
        migrations.CreateModel(
            name='CustomExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('weight', models.FloatField(help_text='0 means bodyweight only.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.baseexercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.sportsman')),
            ],
        ),
        migrations.AddField(
            model_name='userprogram',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='workout_app.customexercise'),
        ),
        migrations.AlterField(
            model_name='baseexercise',
            name='muscle_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.musclegroup'),
        ),
        migrations.DeleteModel(
            name='BaseProgram',
        ),
        migrations.DeleteModel(
            name='UserExercise',
        ),
    ]
