# Generated by Django 5.2 on 2025-04-29 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0008_musclegroup_remove_userprogram_base_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workout_app.sportsmanlevel')),
            ],
        ),
        migrations.CreateModel(
            name='BaseProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.baseexercise')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout_app.baseprogram')),
            ],
            options={
                'unique_together': {('program', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='baseprogram',
            name='exercises',
            field=models.ManyToManyField(related_name='programs', through='workout_app.BaseProgramExercise', to='workout_app.baseexercise'),
        ),
    ]
