# Generated by Django 5.2 on 2025-04-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0009_baseprogram_baseprogramexercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseprogram',
            name='level',
        ),
    ]
