# Generated by Django 5.2 on 2025-05-02 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0010_remove_baseprogram_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogram',
            name='exercises',
        ),
        migrations.AddField(
            model_name='customexercise',
            name='program',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_app.userprogram'),
            preserve_default=False,
        ),
    ]
