# Generated by Django 5.2 on 2025-05-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0013_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsman',
            name='subscription_level',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Pro')], default='free', max_length=10),
        ),
    ]
