# Generated by Django 5.2 on 2025-05-09 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_app', '0016_advertiser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='advertiser',
            name='description',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(default=123, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertiser',
            name='password',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdvertiserAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='workout_app.advertiser')),
            ],
        ),
    ]
